Repository jaipack17/Nature2D, pull requests merged in 2021-12, with the labels that each got.

#15 Add support for Custom RigidBodies
  src/Constants/Globals.lua
  src/Debugging/Restrict.lua
  src/Engine.lua
  src/Physics/Constraint.lua
  src/Physics/RigidBody.lua
  src/Types.lua
Labels: type: enhancement, priority: high, state: in-development

#17 Nature2D Plugin/Utility Modules and SetMaxForce()
  src/Physics/Point.lua
  src/Physics/RigidBody.lua
  src/Plugins/MouseConstraint.lua
  src/Plugins/Quad.lua
  src/Plugins/Triangle.lua
  src/Plugins/init.lua
Labels: type: enhancement, priority: high

#18 Made Connection property `.Connected` public & other Signal changes
  src/Utilities/Signal.lua
Labels: type: enhancement

#20 Use a coil image for visual distinction between springs and ropes/rods.
  README.md
  src/Engine.lua
  src/Physics/Constraint.lua
  src/Utilities/Line.lua
  wally.toml
Labels: type: enhancement, priority: high
